# Generated by Django 4.1.7 on 2023-02-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount_user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
