# Generated by Django 4.1.7 on 2023-02-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_acount_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acount_user',
            name='security_question',
        ),
    ]
