# Generated by Django 4.1.7 on 2023-02-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_acount_user_security_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount_user',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acount_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
