# Generated by Django 4.1.7 on 2023-03-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_acount_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount_user',
            name='calorie_to_eat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='acount_user',
            name='calorie_to_gain',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='acount_user',
            name='desired_weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
