# Generated by Django 4.1.7 on 2023-03-15 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_acount_user_calorie_to_eat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount_user',
            name='maintenance_calorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='securityanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.securityquestion'),
        ),
    ]
