# Generated by Django 4.1.7 on 2023-03-15 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_acount_user_maintenance_calorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acount_user',
            name='calorie_to_eat',
        ),
        migrations.RemoveField(
            model_name='acount_user',
            name='calorie_to_gain',
        ),
        migrations.RemoveField(
            model_name='acount_user',
            name='desired_weight',
        ),
        migrations.RemoveField(
            model_name='acount_user',
            name='maintenance_calorie',
        ),
        migrations.AlterField(
            model_name='securityanswer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCalorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_calorie', models.CharField(blank=True, max_length=10, null=True)),
                ('calorie_to_eat', models.CharField(blank=True, max_length=10, null=True)),
                ('calorie_to_gain', models.CharField(blank=True, max_length=10, null=True)),
                ('desired_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
