# Generated by Django 4.1.7 on 2023-03-15 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_acount_user_calorie_to_eat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalorie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
