# Generated by Django 4.1.7 on 2023-04-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_acount_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.securityquestion'),
        ),
    ]
