# Generated by Django 4.2.11 on 2024-03-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_acount_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCalorie',
        ),
    ]
