# Generated by Django 4.1.7 on 2023-03-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalorieInCommonFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('serving_size', models.CharField(max_length=200)),
                ('number_of_calories', models.IntegerField()),
                ('kj', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalorieMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=200, unique=True)),
                ('cal_plan', models.CharField(max_length=200)),
                ('number_of_calories', models.IntegerField()),
                ('kj', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('range', models.IntegerField()),
                ('cal_plan_1200', models.CharField(max_length=200)),
                ('cal_plan_1500', models.CharField(max_length=200)),
                ('cal_plan_2000', models.CharField(max_length=200)),
                ('time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommonExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('ib_125_person', models.IntegerField()),
                ('ib_155_person', models.IntegerField()),
                ('ib_185', models.IntegerField()),
                ('range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonFoodComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_component', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grocery_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('range', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
