# Generated by Django 4.1.7 on 2023-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfoodcomponents',
            name='calorie_per_gram',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='commonfoodcomponents',
            name='calorie_per_ounce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonfoodcomponents',
            name='kj_per_gram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonfoodcomponents',
            name='kj_per_ounce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calorieincommonfood',
            name='kj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calorieincommonfood',
            name='number_of_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calorieincommonfood',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caloriemealplan',
            name='kj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caloriemealplan',
            name='number_of_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caloriemealplan',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commonexercises',
            name='ib_125_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commonexercises',
            name='ib_155_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commonexercises',
            name='ib_185',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commonexercises',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commonfoodcomponents',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery_list',
            name='range',
            field=models.IntegerField(default=0),
        ),
    ]
