# Generated by Django 4.1.7 on 2023-03-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm_app', '0002_commonfoodcomponents_calorie_per_gram_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grocery_list',
            new_name='GroceryList',
        ),
    ]
