# Generated by Django 4.1.7 on 2023-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_app', '0003_rename_grocery_list_grocerylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='range',
            new_name='end_range',
        ),
        migrations.RenameField(
            model_name='calorieincommonfood',
            old_name='range',
            new_name='end_range',
        ),
        migrations.RenameField(
            model_name='caloriemealplan',
            old_name='range',
            new_name='end_range',
        ),
        migrations.RenameField(
            model_name='commonexercises',
            old_name='range',
            new_name='end_range',
        ),
        migrations.RenameField(
            model_name='commonfoodcomponents',
            old_name='range',
            new_name='end_range',
        ),
        migrations.RenameField(
            model_name='grocerylist',
            old_name='range',
            new_name='end_range',
        ),
        migrations.AddField(
            model_name='calorie',
            name='start_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calorieincommonfood',
            name='start_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caloriemealplan',
            name='start_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonexercises',
            name='start_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonfoodcomponents',
            name='start_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='start_range',
            field=models.IntegerField(default=0),
        ),
    ]
