# Generated by Django 4.1.7 on 2023-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_app', '0004_rename_range_calorie_end_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
