# Generated by Django 4.2.11 on 2024-03-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm_app', '0005_grocerylist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='media/')),
                ('owner_dob', models.DateField()),
                ('car_model', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('date_of_reg', models.DateTimeField()),
                ('region_of_reg', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='reportedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_issue', models.CharField(max_length=100)),
                ('reported_by', models.CharField(blank=True, default='Godwin Owusu', max_length=50, null=True)),
                ('reported_date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('car_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm_app.carinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Calorie',
        ),
        migrations.DeleteModel(
            name='CalorieInCommonFood',
        ),
        migrations.DeleteModel(
            name='CalorieMealPlan',
        ),
        migrations.DeleteModel(
            name='CommonExercises',
        ),
        migrations.DeleteModel(
            name='CommonFoodComponents',
        ),
        migrations.DeleteModel(
            name='GroceryList',
        ),
    ]
