# Generated by Django 4.2.11 on 2024-03-30 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apm_app', '0006_carinfo_reportedcar_delete_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcar',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcar',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportedcar',
            name='reported_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportedcar',
            name='reported_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
