# Generated by Django 4.2.11 on 2024-04-11 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apm_app', '0007_alter_reportedcar_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_dob', models.DateField()),
                ('owner_phone', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_address', models.CharField(max_length=100)),
                ('owner_national_id', models.CharField(max_length=50)),
                ('owner_nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='owner_name',
        ),
        migrations.CreateModel(
            name='EntryCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('entry_time', models.DateTimeField(auto_now=True)),
                ('entry_reason', models.CharField(max_length=100)),
                ('entry_status', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('car_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm_app.carinfo')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm_app.carowner'),
        ),
    ]
